In [1]:
import pandas as pd
import numpy as np

## Ones and zeros

In [8]:
#显示所有列
pd.set_option('display.max_columns', None)
#显示所有行
pd.set_option('display.max_rows', None)
#设置value的显示长度为100，默认为50
pd.set_option('max_colwidth',100)

In [7]:
data=pd.read_clipboard()
data

方法  \
0                     empty(shape[, dtype, order])   
1  empty_like(prototype[, dtype, order, subok, …])   
2                     eye(N[, M, k, dtype, order])   
3                             identity(n[, dtype])   
4                      ones(shape[, dtype, order])   
5       ones_like(a[, dtype, order, subok, shape])   
6                     zeros(shape[, dtype, order])   
7      zeros_like(a[, dtype, order, subok, shape])   
8          full(shape, fill_value[, dtype, order])   
9      full_like(a, fill_value[, dtype, order, …])   

                                                                          意义  
0  Return a new array of given shape and type, without initializing entries.  
1          Return a new array with the same shape and type as a given array.  
2          Return a 2-D array with ones on the diagonal and zeros elsewhere.  
3                                                 Return the identity array.  
4              Return a new array of given shape and type, filled with ones.  
5     Return an array of ones with the same shape and type as a given array.  
6             Return a new array of given shape and type, filled with zeros.  
7    Return an array of zeros with the same shape and type as a given array.  
8        Return a new array of given shape and type, filled with fill_value.  
9         Return a full array with the same shape and type as a given array.

### numpy.identity

numpy.identity(n, dtype=None)  
**Parameters**  
n:int    Number of rows (and columns) in n x n output.  

dtype:data-type, optional   Data-type of the output. Defaults to float.  

Returns
out:ndarray
n x n array with its main diagonal set to one, and all other elements 0.

In [23]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
y=np.arange(3)
print(y)

[0 1 2]


In [26]:
y.dtype

dtype('int32')

In [27]:
x.dtype

dtype('float64')

In [29]:
z=np.array([[0,1,2],[3,4,5],[6,7,8]], dtype=np.float64)
print(z)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [30]:
q=x*z

In [31]:
print(q)

[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]


## From existing data

In [10]:
data=pd.read_clipboard()
data

方法  \
0   array(object[, dtype, copy, order, subok, ndmin])   
1                          asarray(a[, dtype, order])   
2                       asanyarray(a[, dtype, order])   
3                       ascontiguousarray(a[, dtype])   
4                             asmatrix(data[, dtype])   
5                                    copy(a[, order])   
6          frombuffer(buffer[, dtype, count, offset])   
7         fromfile(file[, dtype, count, sep, offset])   
8          fromfunction(function, shape, \*[, dtype])   
9                  fromiter(iterable, dtype[, count])   
10            fromstring(string[, dtype, count, sep])   
11    loadtxt(fname[, dtype, comments, delimiter, …])   

                                                                       意义  
0                                                        Create an array.  
1                                          Convert the input to an array.  
2   Convert the input to an ndarray, but pass ndarray subclasses through.  
3              Return a contiguous array (ndim >= 1) in memory (C order).  
4                                        Interpret the input as a matrix.  
5                               Return an array copy of the given object.  
6                            Interpret a buffer as a 1-dimensional array.  
7                  Construct an array from data in a text or binary file.  
8        Construct an array by executing a function over each coordinate.  
9               Create a new 1-dimensional array from an iterable object.  
10                A new 1-D array initialized from text data in a string.  
11                                            Load data from a text file.

### numpy.fromstring

fromstring(s, dtype)这个函数是比较又意思的，将字符串转换为一个narray对象， 我们先看看这个函数输出情况。
**fromstring(string[, dtype, count, sep])**  
Parameters
string:str A string containing the data.
dtype:data-type, optional
The data type of the array; default: float. For binary input data, the data must be in exactly this format. Most builtin numeric types are supported and extension types may be supported.  
count:int, optional  
Read this number of dtype elements from the data. If this is negative (the default), the count will be determined from the length of the data.  

sep:str, optional
The string separating numbers in the data; extra whitespace between elements is also ignored.

Returns: arrndarray  The constructed array.

Raises  ValueError   If the string is not the correct size to satisfy the requested dtype and count.

In [36]:
s='abcedfg9'
ss=np.fromstring(s,np.int8)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


### numpy.fromfunction

fromfunction(fun, dim)通过自定义函数接口来创建narray对象，fun是一个函数名(看作指针)，dim是一个创建对象的维度。

In [37]:
def fun(i):
    return i%4+1
np.fromfunction(fun,(10,))

array([1., 2., 3., 4., 1., 2., 3., 4., 1., 2.])

## Creating record arrays (numpy.rec)

## Creating character arrays (numpy.char)

## Numerical ranges

In [11]:
data=pd.read_clipboard()
data

方法  \
0          arange([start,] stop[, step,][, dtype])   
1        linspace(start, stop[, num, endpoint, …])   
2  logspace(start, stop[, num, endpoint, base, …])   
3       geomspace(start, stop[, num, endpoint, …])   
4         meshgrid(\*xi[, copy, sparse, indexing])   
5                                            mgrid   
6                                            ogrid   

                                                                       意义  
0                    Return evenly spaced values within a given interval.  
1                 Return evenly spaced numbers over a specified interval.  
2                            Return numbers spaced evenly on a log scale.  
3  Return numbers spaced evenly on a log scale (a geometric progression).  
4                     Return coordinate matrices from coordinate vectors.  
5    nd_grid instance which returns a dense multi-dimensional “meshgrid”.  
6    nd_grid instance which returns an open multi-dimensional “meshgrid”.

### numpy.arange

numpy.arange([start, ]stop, [step, ]dtype=None)

In [14]:
np.arange(3)
np.arange(3,7,2)

array([3, 5])

### numpy.linspace

**numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**    
**Parameters**  
start:array_like  
The starting value of the sequence  .

stop:array_like  
The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.  

num:int, optional  
Number of samples to generate. Default is 50. Must be non-negative.  

endpoint:bool, optional  
If True, stop is the last sample. Otherwise, it is not included. Default is True.如果是True，’stop'是最后的样本。否则，'stop'将不会被包含。默认为true  

retstep:bool, optional  
If True, return (samples, step), where step is the spacing between samples. 会改变计算的输出，输出一个元组，而元组的两个元素分别是需要生成的数列和数列的步进差值。  

dtype:dtype, optional  
The type of the output array. If dtype is not given, infer the data type from the other input arguments.  

axis:int, optional  
The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.  

**Returns**  
samples:ndarray  
There are num equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop) (depending on whether endpoint is True or False).

step:float, optional
Only returned if retstep is True

Size of spacing between samples.

In [15]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [16]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [17]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

## Building matrices

## The Matrix class