In [1]:
import numpy as np
import matplotlib.pyplot as plt 

In [6]:
arr1=np.array([1,2,3],dtype=np.string_)
arr1

array([b'1', b'2', b'3'], dtype='|S1')

## ndarry基础

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [6]:
a[0]=-1   #array是可变容器，这点和list类似
a

array([-1,  2,  3,  4,  5])

In [7]:
a.sum()  #求和

13

In [8]:
a.std()   #standard deviation

2.0591260281974

In [9]:
np.std(a)   #标准差的另一种写法

2.0591260281974

In [10]:
a.cumsum() #累计求和，这点在计算股价连续的收益率的时候十分有用

array([-1,  1,  4,  8, 13], dtype=int32)

In [11]:
a.cumprod()   #累计求乘积，在计算离散的累计收益率时候非常有用

array([  -1,   -2,   -6,  -24, -120], dtype=int32)

<tr><td bgcolor=red>Numpy的切片是一个引用，而不是像list里面的是一个拷贝，因此在处理大规模的数组的时候，这种操作不会带来大量的内存开销 </td></tr>

In [13]:
#如何理解上面的点
a_sub=a[:2]
a_sub

array([-1,  2])

In [14]:
a_sub[0]=1   #修改切片的值

In [15]:
a   #a的值也发生了改变

array([1, 2, 3, 4, 5])

Numpy里面切片出来数据修改会影响数据源

In [16]:
#如何不影响数据源
a_sub_1=a[0:2].copy()

In [17]:
a_sub_1[0]=100
a_sub_1

array([100,   2])

In [18]:
a

array([1, 2, 3, 4, 5])

In [19]:
a[0]='python'   #array的元素必须是相同的类型

ValueError: invalid literal for int() with base 10: 'python'

## Numpy Ndarray的基本属性
.ndim 维度  
.shape 每个维度的长度  
.size 整个数据的长度，等于各个维度长度之积  
.dtype 内部数据的类型  
.itemsize 每个元素的字节长度  
.nbytes 整个数组的字节长度，等于.itemsize*.size

In [20]:
print(a.ndim)
print(a.shape)
print(a.dtype)

1
(5,)
int32


In [21]:
#astype()转换函数
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [22]:
b.dtype

dtype('int32')

In [23]:
b_float=b.astype(np.float)

In [26]:
b_float

array([1., 2., 3., 4.])

In [27]:
b_float.dtype

dtype('float64')

## numpy向量化操作

什么是向量化？Vectoration  


In [28]:
#我们想把list里的数据乘以2
list_1=[0.,0.5,1.5,2.]    #list容器只会重复一遍
list_1*2

[0.0, 0.5, 1.5, 2.0, 0.0, 0.5, 1.5, 2.0]

In [30]:
[i*2 for i in list_1]  #for循环才能达到此目的

[0.0, 1.0, 3.0, 4.0]

In [29]:
c=np.array([0.,0.5,1.5,2.])  #利用numpy的向量化可以很好地解决此问题
c*2

array([0., 1., 3., 4.])

In [31]:
d=np.array(range(4))
d

array([0, 1, 2, 3])

In [32]:
c+d

array([0. , 1.5, 3.5, 5. ])

## numpy通用函数

In [33]:
np.sqrt(2.5)

1.5811388300841898

In [34]:
import math   #利用math包也可以
math.sqrt(2.5)

1.5811388300841898

In [35]:
np.sqrt(c)

array([0.        , 0.70710678, 1.22474487, 1.41421356])

In [36]:
math.sqrt(c)   #math无法对array进行操作

TypeError: only size-1 arrays can be converted to Python scalars

## numpy数据的索引和切片

In [37]:
a

array([1, 2, 3, 4, 5])

In [40]:
a_1=np.array([a,a*2])
a_1

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [42]:
a_1[0,2]   #行和列

3

In [43]:
a_1.sum()  #所有元素求和

45

In [44]:
a_1.sum(axis=0)  #列求和

array([ 3,  6,  9, 12, 15])

In [45]:
a_1.sum(axis=1)  #行求和

array([15, 30])

In [47]:
#条件索引，用于条件选股
year=np.array([[2000,2001,2002],[2005,2006,2007],[2010,2011,2009]])

In [49]:
filter_year=year[year>=2005]
filter_year

array([2005, 2006, 2007, 2010, 2011, 2009])

In [50]:
#多条件索引
filter_year=year[(year>2005)&(year%2==0)]
print(filter_year)

[2006 2010]


In [51]:
#np.where(条件判断，true:,false:)
arr=np.random.randn(3,4)
arr

array([[ 0.53775684,  2.8732008 ,  0.81174274,  0.13546834],
       [-0.08820309, -1.46701048,  3.81402564, -0.7803737 ],
       [ 0.05064319, -0.10268756,  1.12359244,  0.29882475]])

In [52]:
np.where(arr>0,1,-1)    #用于计算策略的sign

array([[ 1,  1,  1,  1],
       [-1, -1,  1, -1],
       [ 1, -1,  1,  1]])

In [53]:
np.sign(arr)   #np.sign()函数能达到同样的效果，用于符号判断

array([[ 1.,  1.,  1.,  1.],
       [-1., -1.,  1., -1.],
       [ 1., -1.,  1.,  1.]])

In [55]:
np.any(arr>0)  #np.any

True

In [56]:
np.array(arr>0)

array([[ True,  True,  True,  True],
       [False, False,  True, False],
       [ True, False,  True,  True]])

In [57]:
np.all(arr>0)  #np.all

False

In [58]:
#reshape
a=np.array(range(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
b=a.reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [61]:
b=np.array(b,dtype=float)