In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

## <font color=#DC143C size=6 face="黑体">Series</font>

In [1]:
data={'country':['China','American','UK'],
      'capital':['Huawei','Blackstone','Bridge'],
      'Population':[1400000000,20000000,50000000]}

In [33]:
s1=pd.Series(data['country'],index=['A','B','C'])
s1

A       China
B    American
C          UK
dtype: object

In [34]:
s1.values

In [34]:
s1.index      #因为我们没有去指明index所以它的index是默认index，那么如何去指明呢

In [48]:
type(s1)        #s1是series

pandas.core.series.Series

### 创建series，方法（一）

In [2]:
s1= pd.Series([1,2,3,4])
s1

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
s1.index   #查看index

RangeIndex(start=0, stop=4, step=1)

In [3]:
s1.values   #查看数据

array([1, 2, 3, 4], dtype=int64)

In [4]:
s1.index

RangeIndex(start=0, stop=4, step=1)

### 创建series，方法（二）

In [5]:
s2=pd.Series(np.arange(10))
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

### 创建series，方法（三）_字典

In [7]:
 s3=pd.Series({'1':1,'2':2,'3':3})
 s3

1    1
2    2
3    3
dtype: int64

In [9]:
s3.values

array([1, 2, 3], dtype=int64)

In [10]:
s3.index

Index(['1', '2', '3'], dtype='object')

In [11]:
s4=pd.Series([1,2,3,4],index=['a','b','c','d'])     #index可以指定，可以改变
s4

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
s4.values

array([1, 2, 3, 4], dtype=int64)

In [13]:
s4.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [14]:
s4['a']

1

In [15]:
s4[s4>2]

c    3
d    4
dtype: int64

In [17]:
s4.to_dict()        #series可以转换成字典

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [18]:
s5=pd.Series(s4.to_dict())    #字典也可以转换成Series

In [19]:
s5

a    1
b    2
c    3
d    4
dtype: int64

In [22]:
index_1=['a','b','c','d','e']
s6=pd.Series(s5,index=index_1)

In [23]:
s6

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [24]:
pd.isnull(s6)

a    False
b    False
c    False
d    False
e     True
dtype: bool

In [25]:
pd.notnull(s6)

a     True
b     True
c     True
d     True
e    False
dtype: bool

In [26]:
s6.name='demo'    #取名字
s6

a    1.0
b    2.0
c    3.0
d    4.0
e    NaN
Name: demo, dtype: float64

## <font color=#DC143C size=6 face="黑体">DataFrame</font>
---
### 方法（一）创建

In [50]:
data={'country':['China','American','UK'],
      'capital':['Huawei','Blackstone','Bridge'],
      'Population':[1400000000,20000000,50000000]}

In [37]:
df1=pd.DataFrame(data)
df1

country     capital  Population
0     China      Huawei  1400000000
1  American  Blackstone    20000000
2        UK      Bridge    50000000

In [40]:
cou=df1['country']    #访问某一列
cou

0       China
1    American
2          UK
Name: country, dtype: object

In [42]:
df1.iterrows()     #访问某行，注意generator是一个生成器，geneator可以通过for循环去取数据

<generator object DataFrame.iterrows at 0x00000224C491D7C8>

In [44]:
for row in df1.iterrows():          #通过for循环，来去行数据
    print(row),print(type(row)),print(len(row))

(0, country            China
capital           Huawei
Population    1400000000
Name: 0, dtype: object)
<class 'tuple'>
2
(1, country         American
capital       Blackstone
Population      20000000
Name: 1, dtype: object)
<class 'tuple'>
2
(2, country             UK
capital         Bridge
Population    50000000
Name: 2, dtype: object)
<class 'tuple'>
2


In [46]:
for row in df1.iterrows():          #特定行
    print(row[0],row[1])
    break

0 country            China
capital           Huawei
Population    1400000000
Name: 0, dtype: object


### 方法（三）通过series创建dataframe

In [54]:
s1=pd.Series(data['country'])   #如果打成s1=pd.Series(data('country'))是错误的
s2=pd.Series(data['capital'])
s3=pd.Series(data['Population'])

In [66]:
df_new=pd.DataFrame([s1,s2,s3],index=['contry','capital','population'])
df_new                             #数据行和列颠倒了

0           1         2
contry           China    American        UK
capital         Huawei  Blackstone    Bridge
population  1400000000    20000000  50000000

In [67]:
df_new1=df_new.T


In [68]:
df_new1

contry     capital  population
0     China      Huawei  1400000000
1  American  Blackstone    20000000
2        UK      Bridge    50000000

In [69]:
df_new1.index=[1,2,3]           #这是改变index的值
df_new1

contry     capital  population
1     China      Huawei  1400000000
2  American  Blackstone    20000000
3        UK      Bridge    50000000

In [71]:
df_new1.columns=['Country','Capital','Population']      #这是改变columns的值
df_new1

Country     Capital  Population
1     China      Huawei  1400000000
2  American  Blackstone    20000000
3        UK      Bridge    50000000

### 方法（三）通过webbrowser方法获取数据

In [3]:
import webbrowser                                    
link='https://www.tiobe.com/tiobe-index/'
webbrowser.open(link)

True

In [4]:
df=pd.read_clipboard()   #从粘贴板解析数据
df

Jun 2019  Jun 2018  Change Programming Language  Ratings Change.1
0         1         1     NaN                 Java  15.004%   -0.36%
1         2         2     NaN                    C  13.300%   -1.64%
2         3         4  change               Python   8.530%   +2.77%
3         4         3  change                  C++   7.384%   -0.95%
4         5         6  change    Visual Basic .NET   4.624%   +0.86%
5         6         5  change                   C#   4.483%   +0.17%
6         7         8  change           JavaScript   2.716%   +0.22%
7         8         7  change                  PHP   2.567%   -0.31%
8         9         9     NaN                  SQL   2.224%   -0.12%
9        10        16  change    Assembly language   1.479%   +0.56%

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.columns    #查看有哪些列

Index(['Jun 2019', 'Jun 2018', 'Change', 'Programming Language', 'Ratings',
       'Change.1'],
      dtype='object')

In [7]:
df.Ratings #查看特定列

0    15.004%
1    13.300%
2     8.530%
3     7.384%
4     4.624%
5     4.483%
6     2.716%
7     2.567%
8     2.224%
9     1.479%
Name: Ratings, dtype: object

In [8]:
df_new=DataFrame(df,columns=[ 'Programming Language', 'Ratings'])
df_new

Programming Language  Ratings
0                 Java  15.004%
1                    C  13.300%
2               Python   8.530%
3                  C++   7.384%
4    Visual Basic .NET   4.624%
5                   C#   4.483%
6           JavaScript   2.716%
7                  PHP   2.567%
8                  SQL   2.224%
9    Assembly language   1.479%

In [9]:
df['Jun 2019']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Jun 2019, dtype: int64

In [10]:
type(df['Jun 2019'])   #每个colum都是一个series

pandas.core.series.Series

In [12]:
df_new1=DataFrame(df,columns=[ 'Programming Language', 'Ratings','Jun 2020']) #创建新的column
df_new1

Programming Language  Ratings  Jun 2020
0                 Java  15.004%       NaN
1                    C  13.300%       NaN
2               Python   8.530%       NaN
3                  C++   7.384%       NaN
4    Visual Basic .NET   4.624%       NaN
5                   C#   4.483%       NaN
6           JavaScript   2.716%       NaN
7                  PHP   2.567%       NaN
8                  SQL   2.224%       NaN
9    Assembly language   1.479%       NaN

In [13]:
df_new1['Jun 2020']=range(0,10)    #给新的列赋值，方法（一）

In [14]:
df_new1

Programming Language  Ratings  Jun 2020
0                 Java  15.004%         0
1                    C  13.300%         1
2               Python   8.530%         2
3                  C++   7.384%         3
4    Visual Basic .NET   4.624%         4
5                   C#   4.483%         5
6           JavaScript   2.716%         6
7                  PHP   2.567%         7
8                  SQL   2.224%         8
9    Assembly language   1.479%         9

In [15]:
df_new1['Jun 2020']=np.arange(0,10)    #给新的列赋值，方法（二）

In [16]:
df_new1

Programming Language  Ratings  Jun 2020
0                 Java  15.004%         0
1                    C  13.300%         1
2               Python   8.530%         2
3                  C++   7.384%         3
4    Visual Basic .NET   4.624%         4
5                   C#   4.483%         5
6           JavaScript   2.716%         6
7                  PHP   2.567%         7
8                  SQL   2.224%         8
9    Assembly language   1.479%         9

In [17]:
df_new1['Jun 2020']=pd.Series(np.arange(0,10))    #给新的列赋值，方法（三）
df_new1

Programming Language  Ratings  Jun 2020
0                 Java  15.004%         0
1                    C  13.300%         1
2               Python   8.530%         2
3                  C++   7.384%         3
4    Visual Basic .NET   4.624%         4
5                   C#   4.483%         5
6           JavaScript   2.716%         6
7                  PHP   2.567%         7
8                  SQL   2.224%         8
9    Assembly language   1.479%         9

In [21]:
df_new1['Jun 2020']=pd.Series([10,11],index=[1,2])   #改变某列某个数目
df_new1

Programming Language  Ratings  Jun 2020
0                 Java  15.004%       NaN
1                    C  13.300%      10.0
2               Python   8.530%      11.0
3                  C++   7.384%       NaN
4    Visual Basic .NET   4.624%       NaN
5                   C#   4.483%       NaN
6           JavaScript   2.716%       NaN
7                  PHP   2.567%       NaN
8                  SQL   2.224%       NaN
9    Assembly language   1.479%       NaN

## 补充：<font color=#DC143C size=5 face="黑体">dataframe的命名</font>
---
### 一般常用的有两个方法：
1、使用DataFrame.index = [newName]，DataFrame.columns = [newName]，这两种方法可以轻松实现。  
2、使用rename方法（推荐)  
DataFrame.rename(mapper=None, index=None, columns=None, axis=None, copy=True, inplace=False, level=None)  
参数：  
mapper, index, columns : 映射的规则。  
axis：指定轴，可以是轴名称（'index'，'columns'）或数字（0,1），默认为index。  
copy：布尔值，默认为True，复制底层数据。  
inplace：布尔值，默认为False。指定是否返回新的DataFrame。如果为True，则在原df上修改，返回值为None。  
level：int或level name，默认为None。如果是MultiIndex，只重命名指定级别的标签。  
返回值：Return

In [72]:
df10= DataFrame(np.arange(9).reshape(3, 3), index = ['bj', 'sh', 'gz'], columns=['a', 'b', 'c'])
print(df10)

    a  b  c
bj  0  1  2
sh  3  4  5
gz  6  7  8
