In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# Different ways of creating DataFrame

In [18]:
#df = pd.read_csv("weather_data.csv")
#df

In [19]:
#df=pd.read_excel("weather_data.xlsx","Sheet1")
#df

In [2]:
weather_data = {                     #From python dictionary
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df = pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [3]:
weather_data = [                     #From Tuples
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'],index=[1,2,3])
df

day  temperature  windspeed  event
1  1/1/2017           32          6   Rain
2  1/2/2017           35          7  Sunny
3  1/3/2017           28          2   Snow

In [22]:
weather_data = [                                     #From list of dictionaries
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'],index=[1,2,3])
df

day  temperature  windspeed  event
1  1/1/2017           32          6   Rain
2  1/2/2017           35          7  Sunny
3  1/3/2017           28          2   Snow

## 例子1


In [8]:
pd.DataFrame({'id':[100,101,102],'color':['red','blue','black']})  # from dictionary

id  color
0  100    red
1  101   blue
2  102  black

In [9]:
pd.DataFrame({'id':[100,101,102],'color':['red','blue','black']},columns=['color','id'])

color   id
0    red  100
1   blue  101
2  black  102

In [10]:
pd.DataFrame({'id':[100,101,102],'color':['red','blue','black']},index=list('abc'))

id  color
a  100    red
b  101   blue
c  102  black

In [24]:
df=pd.DataFrame({'id':[100,101,102],'color':['red','blue','black']},index=['a','b','c'])
df

id  color
a  100    red
b  101   blue
c  102  black

In [13]:
pd.DataFrame([[100,'red'],[101,'blue'],[102,'red']])   

0     1
0  100   red
1  101  blue
2  102   red

## 例子2

In [20]:
arr=np.random.rand(4,2)
arr

array([[0.50659504, 0.42516349],
       [0.85890233, 0.09037664],
       [0.84217777, 0.03715713],
       [0.9139559 , 0.26968069]])

In [22]:
pd.DataFrame(arr,columns=[1,2])

1         2
0  0.506595  0.425163
1  0.858902  0.090377
2  0.842178  0.037157
3  0.913956  0.269681

## 例子3

In [23]:
pd.DataFrame({'student':np.arange(100,110,1),'test':np.random.randint(60,101,10)})

student  test
0      100    86
1      101    69
2      102    76
3      103    89
4      104    63
5      105   100
6      106    62
7      107    79
8      108    85
9      109    84

In [6]:
pd.DataFrame({'student':np.arange(100,110,1),'test':np.random.randint(60,101,10)}).set_index('student')

test
student      
100        80
101        73
102        84
103        77
104        74
105        93
106        64
107        77
108        73
109        98

## 将dataframe和series融合

In [26]:
s=pd.Series(['round','square'],index=['c','b'],name='shape')
s

c     round
b    square
Name: shape, dtype: object

In [27]:
df

id  color
a  100    red
b  101   blue
c  102  black

In [28]:
pd.concat([df,s])

0  color     id
a     NaN    red  100.0
b     NaN   blue  101.0
c     NaN  black  102.0
c   round    NaN    NaN
b  square    NaN    NaN

In [30]:
pd.concat([df,s],axis=1)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


id  color   shape
a  100    red     NaN
b  101   blue  square
c  102  black   round

## Fast creat examples:

In [9]:
pd.DataFrame({'col_one':[10, 20], 'col_two':[30, 40]},index=list('ab'))

col_one  col_two
a       10       30
b       20       40

In [8]:
pd.DataFrame(np.random.rand(2, 3),index=(1,2),columns=list('abc'))

a         b         c
1  0.297633  0.405570  0.305068
2  0.805474  0.608688  0.242698

In [10]:
pd.DataFrame(np.random.randn(3))

0
0 -0.910096
1 -0.307862
2  0.175245

In [25]:
pd.util.testing.makeMixedDataFrame()

A    B     C          D
0  0.0  0.0  foo1 2009-01-01
1  1.0  1.0  foo2 2009-01-02
2  2.0  0.0  foo3 2009-01-05
3  3.0  1.0  foo4 2009-01-06
4  4.0  0.0  foo5 2009-01-07

## RAND函数

In [11]:
np.random.rand(4,3,2)  #生成指定维度的的[0,1)范围之间的随机数，输入参数为维度

array([[[0.64352214, 0.04354724],
        [0.31701921, 0.18050474],
        [0.54308451, 0.21063975]],

       [[0.40135701, 0.68624273],
        [0.49916001, 0.26372779],
        [0.26206664, 0.21505936]],

       [[0.92151279, 0.07847775],
        [0.70642926, 0.23337541],
        [0.91438039, 0.38344327]],

       [[0.94264022, 0.39997593],
        [0.59599325, 0.76545847],
        [0.10169898, 0.70639936]]])

In [12]:
np.random.randn(2,4)    #生成指定维度的服从标准正态分布的随机数，输入参数为维度

array([[ 0.54930642, -1.61496543,  0.13312906, -0.21153673],
       [ 0.35983971,  1.03130366,  1.51490009,  0.65160401]])

In [13]:
np.random.randint(1,size=5)      #返回随机数或者随机数组成的array

array([0, 0, 0, 0, 0])

In [15]:
np.random.randint(1,5,size=5)

array([1, 2, 4, 1, 1])

In [11]:
np.random_integer(1,size=5)     #返回范围为[low,high] 闭区间 随机整数

AttributeError: module 'numpy' has no attribute 'random_integer'

In [18]:
np.random.random(size = (2,2))  #生成随机浮点数阵列

array([[0.28338698, 0.59584378],
       [0.14303318, 0.34108891]])

In [27]:
np.random.choice(5,3)   #从给定数组a中随机选择,p可以指定a中每个元素被选择的概率

array([3, 1, 4])

In [26]:
np.random.choice(5,3,replace=False)  #当replace = False时，返回的数中不可以有重复的

array([1, 4, 3])

In [22]:
np.random.choice(5,size = (3,2))

array([[1, 1],
       [4, 2],
       [4, 4]])

# Read_write excel:

In [20]:
df=pd.read_excel('D:/临时/stock_data.xlsx',columns=['Company', 'a', 'b', 'c','d'])
df

stock-data     Unnamed: 1 Unnamed: 2 Unnamed: 3     Unnamed: 4
0    tickers            eps    revenue      price         people
1      GOOGL          27.82         87        845     larry page
2        WMT           4.61        484         65           n.a.
3       MSFT             -1         85         64     bill gates
4        RIL  not available         50       1023  mukesh ambani
5       TATA            5.6         -1       n.a.     ratan tata

### 读取数据

In [26]:
df=pd.read_excel('D:/临时/stock_data.xlsx',skiprows=1)
df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [67]:
df=pd.read_excel('D:/临时/stock_data.xlsx',header=1)      #skiprows/header  are kind of same

df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [58]:
df=pd.read_excel('D:/临时/stock_data.xlsx',sheet_name='Sheet2',header=None )      #如果数据在sheet2
df

0              1        2      3              4
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

### 将无用数据定义为'nan'

In [68]:
df.replace(["n.a.", "not available"], np.nan, regex=True)         #替换法，替换n.a,not available 为Nan


tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3     RIL    NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [69]:
df=pd.read_excel('D:/临时/stock_data.xlsx',header=1,nrows=3)        #nrows表示截取前几行
df

tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

### 导出数据

In [72]:
df.to_csv('new.csv',index=False)   #注意格式

In [73]:
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [74]:
df.to_csv('new.csv',index=False,columns=['tickers','eps'])   #理解意义

### 加入函数

In [95]:
df_1=pd.read_excel('D:/临时/stock_data.xlsx',index=[1,2,3,4,5],header=1)
df_1

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [98]:
def convert_people_cell(cell):
    if cell==['n.a','not available']:
        return 'Sam Walton'
    return cell

def convert_price_cell(cell):
    if cell=="n.a":
        return 50
    return cell
    
df_1= pd.read_excel("D:/临时/stock_data.xlsx","Sheet1",header=1, converters= {
        'people': convert_people_cell,
        'price': convert_price_cell
    })
df_1

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [107]:
df_1.to_excel('new.xlsx',sheet_name='Sheet2',startrow=2, startcol=1,index=False)  # to_excel与to_csv有很大的不同，比如后缀名，csv是没有sheet_name函数的

### 把两个数据写进一个excel表格里面

In [114]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [115]:
with pd.ExcelWriter('D:/临时/absstocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks",index=False)
    df_weather.to_excel(writer, sheet_name="weather",index=False)